### PR TITLE
Create flathub.json

### PR DESCRIPTION
**Pull request by alainm23**

### CODE REVIEW

**Comment by hfiguiere** [comment]
build fail because appstream file point to screenshot on `master` branch which is never a good idea.

pointing to `6a8445fecbd39e4332e7ff2f45b4eee0c5284b2e` should probably work.


Shall also this be EOL rebase to `io.github.alainm23.planify` ?

**Comment by hfiguiere** [comment]
Pushed a commit to fix the build.

The rebase would allow the transition to the new package automatically and should be done here.

**Comment by hfiguiere** [comment]
@alainm23 let me know if you agree with the "rebase".

**Comment by hfiguiere** [comment]
```patch
diff --git a/flathub.json b/flathub.json
index fc519f9..0a32c2e 100644
--- a/flathub.json
+++ b/flathub.json
@@ -1,3 +1,4 @@
 {
-    "end-of-life": "This wrapper is no longer maintained because of incompatibilities with the official release"
+    "end-of-life": "This wrapper is no longer maintained because of incompatibilities with the official release",
+    "end-of-life-rebase": "io.github.alainm23.planify"
 }
```

that's the extra patch, I can push it.

**Comment by bbhtt** [comment]
bot, build

**Pull request merged**
